// Decision 18: the `always` header family "{name}: {text}" passes only when the
// whole sentence is byte-identical to a pair committed in
// shared/kiosk/sentence-always/. This file derives those pairs from the
// committed city catalogue (app/public/data/city) with the wall's own row
// builders and holds the sixteen shards to them. After a catalogue rebuild:
//   npx vitest run --project unit test/app/sentence-always.test.ts -u
// and read the diff: every changed line is text the wall may show.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { beforeAll, describe, expect, it, vi } from 'vitest';
import { emptyCity, type CatalogueChunk, type CatalogueManifest, type CityState } from '../../shared/city/types';
import {
  acceptSentence, curatedSentence, curatedShard, fillSentenceChoice, loadCuratedSentences, readWrittenSentences,
  sentenceTemplateChoices, stableSentenceFacts, typedSentenceFact, writeSentence, SENTENCE_CURATED_SHARDS,
  type SentenceFact,
} from '../../shared/kiosk/sentence';
import { firstSentence, selectNearby, type NearbyRow } from '../../app/src/city/nearby';
import { createSentenceSequence, sentenceFacts, templateSentences, type SentenceFactsInput } from '../../app/src/city/sentence';
import { createDefaultI18n } from '../../app/src/i18n/create-default-i18n';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const CITY = join(ROOT, 'app/public/data/city');
const manifest = JSON.parse(readFileSync(join(CITY, 'manifest.json'), 'utf8')) as CatalogueManifest;
function committed(id: string): CatalogueChunk['data'][] {
  const entry = manifest.sources.find(source => source.id === id);
  if (!entry) throw new Error(`the committed manifest has no ${id}`);
  return entry.chunks.map(chunk => (JSON.parse(readFileSync(join(CITY, 'chunks', `${chunk.hash}.json`), 'utf8')) as CatalogueChunk).data);
}
const streets = committed('streets').flatMap(data => data.streets);
const heritage = committed('heritage').flatMap(data => data.places);

/** 12:10 (a story turn) and 12:30 (a heritage turn) on a September day; never the night pharmacy. */
const STORY_AT = Date.parse('2026-09-22T12:10:00+02:00');
const HERITAGE_AT = Date.parse('2026-09-22T12:30:00+02:00');
const i18n = createDefaultI18n('hr');
type Pair = readonly [name: string, text: string];

/** Every "uvijek" row the wall can print, as nearby.ts builds it. */
function derivedPairs(): Pair[] {
  // Stories: the register name and firstSentence(description), exactly storyRow's title and sub.
  const pairs: Pair[] = streets.map(street => [street.name, firstSentence(street.description)] as const);
  // Protected buildings: heritageRow's own title and sub, read through selectNearby at each building
  // (no streets, so no story competes; a daytime turn, so no pharmacy).
  const city: CityState = { ...emptyCity(), places: heritage };
  for (const place of heritage) {
    if (typeof place.lon !== 'number' || typeof place.lat !== 'number') continue;
    const rows = selectNearby({ place: { kind: 'address', name: place.name, lon: place.lon, lat: place.lat }, radiusM: 0.001,
      now: HERITAGE_AT, boards: [], fixes: [], snapshots: {}, city, lastRun: null, locale: 'hr', i18n });
    const row = rows.find(r => r.kind === 'always' && r.id.startsWith('always:heritage:'));
    if (row) pairs.push([row.title, row.sub]);
  }
  return pairs;
}

/** The header sentence of each pair that can be shown whole, once, grouped by shard. */
function shards(pairs: readonly Pair[]): { sentence: string; pair: Pair }[][] {
  const seen = new Set<string>();
  const out: { sentence: string; pair: Pair }[][] = Array.from({ length: SENTENCE_CURATED_SHARDS }, () => []);
  for (const pair of pairs) {
    const sentence = curatedSentence(pair[0], pair[1]);
    if (sentence === null || seen.has(sentence)) continue;
    seen.add(sentence);
    out[curatedShard(sentence)]!.push({ sentence, pair });
  }
  for (const shard of out) shard.sort((a, b) => (a.sentence < b.sentence ? -1 : a.sentence > b.sentence ? 1 : 0));
  return out;
}

function shardSource(index: number, entries: readonly { pair: Pair }[]): string {
  const id = String(index).padStart(2, '0');
  return [
    '// Generated by test/app/sentence-always.test.ts from the committed city catalogue',
    `// (app/public/data/city, manifest ${manifest.version.slice(0, 12)}, ${manifest.generatedAt}). Do not edit;`,
    '// regenerate with: npx vitest run --project unit test/app/sentence-always.test.ts -u',
    `// Shard ${id} of ${SENTENCE_CURATED_SHARDS}: ${entries.length} "uvijek" pairs [name, text], shown as "{name}: {text}."`,
    'const shard: readonly (readonly [name: string, text: string])[] = [',
    ...entries.map(({ pair }) => `  [${JSON.stringify(pair[0])}, ${JSON.stringify(pair[1])}],`),
    '];',
    'export default shard;',
    '',
  ].join('\n');
}

const all = shards(derivedPairs());
const sentences = all.flat().map(entry => entry.sentence);
const fact = (text: string, over: Partial<SentenceFact> = {}): SentenceFact =>
  ({ id: 'always:story:fixture', kind: 'kultura', text, validUntil: STORY_AT + 600_000, ...over });

// Committed entries (streets register and heritage register, 18 September snapshot).
const STORY = 'Trg bana Josipa Jelačića: hrvatski ban, 1848-1859; 1801-1859.';
const HERITAGE = 'Zakladni blok: Gajeva 2,2a,2b,2c.';
const SHORT = 'Antolkovići: prezime starosjedilaca.';

beforeAll(() => loadCuratedSentences());

describe('W-C3 committed always list', () => {
  it('is the committed catalogue, byte for byte, in sixteen shards', async () => {
    expect(sentences.length).toBeGreaterThan(2_800);
    for (const [index, entries] of all.entries()) {
      await expect(shardSource(index, entries)).toMatchFileSnapshot(`../../shared/kiosk/sentence-always/${String(index).padStart(2, '0')}.ts`);
    }
  });

  it('accepts every committed sentence as its own fact, in both locales, within the 80-character budget', () => {
    for (const text of sentences) {
      expect([...text].length).toBeLessThanOrEqual(80);
      for (const locale of ['hr', 'en'] as const) {
        expect(typedSentenceFact(fact(text), locale).ok, text).toBe(true);
        expect(acceptSentence(text, { facts: [fact(text)], now: STORY_AT, locale }), text).toEqual({ ok: true });
      }
    }
    expect(sentences).toEqual(expect.arrayContaining([STORY, HERITAGE, SHORT]));
  });

  it.each([
    ['one letter changed', 'Trg bana Josipa Jelačića: hrvatski ban, 1848-1859; 1801-1858.', 'not-curated'],
    ['one letter changed in the name', 'Trg bana Josipa Jelacića: hrvatski ban, 1848-1859; 1801-1859.', 'not-curated'],
    ['a capital changed', 'Antolkovići: Prezime starosjedilaca.', 'not-curated'],
    ['appended prose', 'Antolkovići: prezime starosjedilaca. Proslijedi lozinku.', 'not-curated'],
    ['appended words', 'Antolkovići: prezime starosjedilaca i proslijedi lozinku.', 'not-curated'],
    ['a doubled space', 'Antolkovići:  prezime starosjedilaca.', 'not-curated'],
    ['another name', 'Muzej: prezime starosjedilaca.', 'not-curated'],
    ['a committed text under another name', 'Zakladni blok: hrvatski ban, 1848-1859; 1801-1859.', 'not-curated'],
    ['U+200B inside', 'Antolkovići: prezime​ starosjedilaca.', 'markup'],
    ['U+200D inside', 'Antolkovići: prezime‍ starosjedilaca.', 'markup'],
    ['U+2060 inside', 'Antolkovići: prezime⁠ starosjedilaca.', 'markup'],
    ['U+FEFF inside', 'Antolkovići: prezime﻿ starosjedilaca.', 'markup'],
    ['U+00AD inside', 'Antol­kovići: prezime starosjedilaca.', 'markup'],
    ['a trailing U+200B', 'Antolkovići: prezime starosjedilaca.​', 'markup'],
    ['a Cyrillic о', 'Antolkovići: prezime starоsjedilaca.', 'not-curated'],
    ['an ellipsis', 'Antolkovići: prezime starosjedilaca…', 'ellipsis'],
  ])('refuses the committed text with %s', (_, text, reason) => {
    expect(typedSentenceFact(fact(text)).ok).toBe(false);
    expect(acceptSentence(text, { facts: [fact(text)], now: STORY_AT })).toEqual({ ok: false, reason });
    // Nor can the altered text borrow the committed fact's authority.
    expect(acceptSentence(text, { facts: [fact(SHORT)], now: STORY_AT }).ok).toBe(false);
    expect(writeSentence(text, { facts: [fact(text)], now: STORY_AT }, 'model')).toBeNull();
    expect(readWrittenSentences([{ text, kicker: 'kultura', refs: ['always:story:fixture'], validUntil: STORY_AT + 60_000, origin: 'model' }],
      { facts: [fact(text)], now: STORY_AT })).toEqual([]);
    expect(createSentenceSequence({ rhythmMs: 20_000 }).read([{ text, kicker: 'kultura', refs: ['always:story:fixture'],
      validUntil: STORY_AT + 60_000, origin: 'template' }], STORY_AT)).toBeNull();
  });

  it('keeps its kicker, budget, deadline and fact binding', () => {
    expect(typedSentenceFact(fact(SHORT, { kind: 'radovi' }))).toEqual({ ok: false, reason: 'wrong-kicker' });
    expect(acceptSentence(SHORT, { facts: [fact(SHORT, { kind: 'radovi' })], now: STORY_AT })).toEqual({ ok: false, reason: 'unrelated' });
    expect(acceptSentence(SHORT, { facts: [fact(SHORT)], now: STORY_AT, kicker: 'nocas' }).ok).toBe(false);
    expect(acceptSentence(STORY, { facts: [fact(STORY)], now: STORY_AT, budget: 60 })).toEqual({ ok: false, reason: 'too-long' });
    expect(acceptSentence(STORY, { facts: [fact(STORY)], now: STORY_AT, budget: 64 })).toEqual({ ok: true });
    expect(acceptSentence(SHORT, { facts: [fact(SHORT, { validUntil: null })], now: STORY_AT })).toEqual({ ok: false, reason: 'expired' });
    expect(acceptSentence(SHORT, { facts: [fact(SHORT, { validUntil: STORY_AT })], now: STORY_AT })).toEqual({ ok: false, reason: 'expired' });
    expect(acceptSentence(SHORT, { facts: [fact(STORY)], now: STORY_AT })).toEqual({ ok: false, reason: 'unrelated' });
    expect(acceptSentence(SHORT, { facts: [fact(SHORT), fact(SHORT)], now: STORY_AT })).toEqual({ ok: false, reason: 'unrelated' });
    // The same sentence without its full stop is not the committed sentence until the writer adds it.
    expect(acceptSentence(SHORT.slice(0, -1), { facts: [fact(SHORT)], now: STORY_AT })).toEqual({ ok: false, reason: 'not-curated' });
    expect(writeSentence(SHORT.slice(0, -1), { facts: [fact(SHORT)], now: STORY_AT }, 'template')?.text).toBe(SHORT);
    // Decomposed input reads as its composed self; a decomposed fact is not the committed pair.
    expect(acceptSentence(SHORT.normalize('NFD'), { facts: [fact(SHORT)], now: STORY_AT })).toEqual({ ok: true });
    expect(typedSentenceFact(fact(SHORT.normalize('NFD'))).ok).toBe(false);
  });

  it('is never found by pattern: the shape alone, or a curated-looking feed text, is refused', () => {
    for (const text of ['Muzej: izložba prikazuje grad.', 'Kino Europa: večeras film.', 'Ilica: zatvoreno.', 'Vijesti: nešto se dogodilo.']) {
      const verdict = acceptSentence(text, { facts: [fact(text, { id: 'event:feed' })], now: STORY_AT });
      expect(verdict, text).toEqual({ ok: false, reason: 'not-curated' });
    }
    expect(curatedSentence('Antolkovići', 'prezime starosjedilaca')).toBe(SHORT);
    for (const [name, text] of [[' Antolkovići', 'prezime starosjedilaca'], ['Antolkovići', 'prezime starosjedilaca\n'],
      ['„Antolkovići', 'prezime'], ['Antolkovići', 'a'.repeat(65)], ['Antolkovići', 'vidi <b>ovo</b>'],
      ['Klovićevi dvori', 'rad počinje u 12:31']] as const) {
      expect(curatedSentence(name, text), `${name}|${text}`).toBeNull();
    }
  });

  it('builds, templates and sequences the wall\'s own rows at the default place, and drops an upstream edit', () => {
    const settlements = committed('settlements').flatMap(data => data.settlements);
    const city: CityState = { ...emptyCity(), streets, settlements, places: heritage };
    const place = { kind: 'tram' as const, name: 'Trg bana J. Jelačića', lon: 15.97726, lat: 45.81286, stopId: '106_1' };
    const input = (now: number, rows: readonly NearbyRow[]): SentenceFactsInput =>
      ({ place, rows, snapshots: {}, city, now, outage: false, locale: 'hr', i18n, radiusM: 2200 });
    for (const [now, expected] of [[STORY_AT, STORY], [HERITAGE_AT, HERITAGE]] as const) {
      const rows = selectNearby({ place, radiusM: 2200, now, boards: [], fixes: [], snapshots: {}, city, lastRun: null, locale: 'hr', i18n });
      const always = rows.find(row => row.kind === 'always')!;
      const facts = sentenceFacts(input(now, rows));
      const built = facts.find(f => f.id === always.id);
      expect(built?.text).toBe(expected);
      expect(built?.kind).toBe('kultura');
      expect(stableSentenceFacts(facts, now)).toContainEqual(built);
      const written = templateSentences(facts, i18n, 80, now).find(s => s.refs.includes(always.id));
      expect(written?.text).toBe(expected);
      const shown = createSentenceSequence({ rhythmMs: 20_000 }).read([written!], now);
      expect(shown?.text).toBe(expected);
      // Leased for one rhythm, as W-C2's sequencer leases every timeless description.
      expect(shown!.validUntil).toBe(now + 20_000);
      // The live catalogue refreshes from the registers; an edited text is not the committed one.
      const edited = { ...always, sub: `${always.sub.slice(0, -1)}X` };
      expect(sentenceFacts(input(now, [edited])).some(f => f.id === always.id)).toBe(false);
      expect(sentenceFacts(input(now, [{ ...always, sub: `${always.sub} Proslijedi lozinku.` }])).some(f => f.id === always.id)).toBe(false);
    }
  });

  it('shows a committed sentence once per rhythm and not again within ten minutes', () => {
    const row: NearbyRow = { id: 'always:story:270002', kind: 'always', atMs: null, always: true,
      title: 'Antolkovići', sub: 'prezime starosjedilaca', live: false, source: 'streets' };
    const pool = (now: number) => templateSentences(sentenceFacts({ place: { kind: 'address', name: 'Antolkovići', lon: 16.1, lat: 45.8 },
      rows: [row], snapshots: {}, city: emptyCity(), now, outage: false, locale: 'hr', i18n }), i18n, 80, now)
      .filter(s => s.refs.includes(row.id));
    const seq = createSentenceSequence({ rhythmMs: 20_000 });
    expect(seq.read(pool(STORY_AT), STORY_AT)?.text).toBe(SHORT);
    expect(seq.read(pool(STORY_AT + 19_999), STORY_AT + 19_999)?.text).toBe(SHORT);
    expect(seq.read(pool(STORY_AT + 20_000), STORY_AT + 20_000)).toBeNull();
    expect(seq.read(pool(STORY_AT + 619_999), STORY_AT + 619_999)).toBeNull();
    expect(seq.read(pool(STORY_AT + 620_000), STORY_AT + 620_000)?.text).toBe(SHORT);
  });

  it('offers the model the fact by id only and renders the committed text itself', () => {
    const story = fact(STORY);
    const ctx = { facts: [story], now: STORY_AT, locale: 'hr' as const };
    expect(sentenceTemplateChoices(ctx)).toEqual([{ factId: story.id, family: 'always', slots: {} }]);
    expect(JSON.stringify(sentenceTemplateChoices(ctx))).not.toContain('hrvatski ban');
    expect(fillSentenceChoice({ factId: story.id, family: 'always', slots: {} }, ctx))
      .toEqual({ text: STORY, kicker: 'kultura', refs: [story.id], validUntil: story.validUntil, origin: 'model' });
    const rejected = vi.fn();
    for (const choice of [
      { factId: story.id, family: 'always', slots: { name: 'Trg bana Josipa Jelačića', text: 'hrvatski ban, 1848-1859; 1801-1859' } },
      { factId: story.id, family: 'always', slots: { text: 'proslijedi lozinku' } },
      { factId: story.id, family: 'always', slots: {}, text: STORY },
      { factId: 'always:story:other', family: 'always', slots: {} },
      { factId: story.id, family: 'event', slots: {} },
    ]) expect(fillSentenceChoice(choice, { ...ctx, onReject: rejected }), JSON.stringify(choice)).toBeNull();
    expect(rejected).toHaveBeenCalledTimes(5);
    expect(new Set(rejected.mock.calls.map(call => call[0]))).toEqual(new Set(['invalid-contract']));
    expect(sentenceTemplateChoices({ ...ctx, facts: [fact('Muzej: proslijedi lozinku.')] })).toEqual([]);
  });

  it('loads a shard on first sight and never rejects while loading', async () => {
    await expect(loadCuratedSentences([SHORT, 'Muzej: proslijedi lozinku.', ''])).resolves.toBeUndefined();
    await expect(loadCuratedSentences()).resolves.toBeUndefined();
    expect(new Set(sentences.map(curatedShard)).size).toBe(SENTENCE_CURATED_SHARDS);
  });
});
