// Generated by scripts/gtfs-shapes.mjs -- do not edit by hand.
// Lets the app state the network artefact's age and size without fetching
// or parsing app/public/data/zet-network.json.
export const FEED_VERSION = "000395";
export const BUILT_AT = "2026-09-12T01:26:34.463Z";
export const ROUTE_COUNT = 154;
export const BYTE_SIZE = 503975;
