// ISO 4217 alphabetic codes, including fund/metal/test codes and withdrawn
// currencies: a historical payment is still a payment vector.
// Baseline: Debian iso-codes' ISO 4217 data (active and historic entries);
// additional codes XAD, XCG and ZWG are included explicitly. This is a data pin,
// not a runtime dependency on Intl's implementation-specific currency list.
export const ISO_4217_CODES = `
ADF ADP AED AFA AFN ALK ALL AMD ANG AOA AOK AON AOR ARA ARL ARM ARP ARS
ATS AUD AWG AZM AZN BAD BAM BBD BDT BEC BEF BEL BGJ BGK BGL BGN BHD BIF
BMD BND BOB BOP BOV BRB BRC BRE BRL BRN BRR BSD BTN BUK BWP BYB BYN BYR BZD
CAD CDF CHE CHF CHW CLF CLP CNX CNY COP COU CRC CSD CSJ CSK CUC CUP CVE
CZK DDM DEM DJF DKK DOP DZD ECS ECV EGP ERN ESA ESB ESP ETB EUR FIM FJD
FKP FRF GBP GEK GEL GHC GHS GIP GMD GNE GNF GNS GQE GRD GTQ GWE GWP GYD
HKD HNL HRD HRK HTG HUF IDR IEP ILP ILR ILS INR IQD IRR ISJ ISK ITL JMD
JOD JPY KES KGS KHR KMF KPW KRW KWD KYD KZT LAJ LAK LBP LKR LRD LSL LSM
LTL LTT LUC LUF LUL LVL LVR LYD MAD MAF MDL MGA MGF MKD MLF MMK MNT MOP MRO MRU MTP
MUR MVQ MVR MWK MXN MXP MXV MYR MZE MZM MZN NAD NGN NIC NIO NLG NOK NPR
NZD OMR PAB PEH PEI PEN PES PGK PHP PKR PLN PLZ PTE PYG QAR RHD ROK ROL
RON RSD RUB RUR RWF SAR SBD SCR SDD SDG SDP SEK SGD SHP SIT SKK SLE SLL
SOS SRD SRG SSP STD STN SUR SVC SYP SZL THB TJR TJS TLE TMM TMT TND TOP TRL TRY
TTD TWD TZS UAH UAK UGS UGW UGX USD USN USS UYI UYN UYP UYU UYW UZS VEB VED VEF
VES VNC VND VUV WST XAD XAF XAG XAU XBA XBB XBC XBD XCD XCG XDR XEU XFO XFU XOF XPD
XPF XPT XRE XSU XTS XUA XXX YDD YER YUD YUM YUN ZAL ZAR ZMK ZMW ZRN ZRZ ZWD ZWG ZWL ZWN ZWR
`.trim().split(/\s+/u);
