// Every Croatian string of /snimka/, verbatim from docs/snimka-2026-10.md
// section 11 and the v2 plan's Appendix B (2 October 2026), nested by the
// dot path of its key (SN.badge.counts). The page is Croatian only, so there
// is no catalogue and no locale: the strings live here, in one object, for
// the owner's read-through. `{name}` is a placeholder for fill(). "štrajk"
// stands only under narration.* and sources.* (test/app/snimka-strings.test.ts
// holds the rules). A v1 key a v1 module still imports stays until its lane
// retires it.
import type { Speed } from '../../../shared/snimka';

export const SN = {
  page: {
    title: 'Kaj ima? · Snimka',
    description: 'Snimka dana bez tramvaja i autobusa u Zagrebu, od 27. rujna do 2. listopada 2026., iz podataka aplikacije Kaj ima?: što se događalo, što je zaslon govorio i koji su podaci iz toga nastali.',
    name: 'Snimka',
  },
  nav: {
    summary: 'Ukratko',
    stage: 'Snimka',
    numbers: 'Brojke',
    screen: 'Zaslon',
    strip: 'Tijek',
    alternatives: 'Zamjene',
    reckoning: 'Što se vidjelo',
    open: 'Otvoreni podaci',
    sources: 'Izvori',
  },
  hero: {
    eyebrow: 'Snimka · 27. rujna do 2. listopada 2026.',
    title: 'Tri dana bez tramvaja',
  },
  narration: {
    lede1: 'Radnici ZET-a i Zagrebačkog holdinga stupili su u štrajk u ponedjeljak 28. rujna u 03:30. Županijski sud u Zagrebu u srijedu 30. rujna proglasio je oba štrajka nezakonitima, a iste su se večeri tramvaji i autobusi vratili na ulice.',
    lede2: 'Ova stranica ponavlja te dane iz podataka koje je aplikacija imala, minutu po minutu: vozila na karti, bicikle na stanicama, zatvorene ulice, obavijesti ZET-a, presude, naslove i rečenicu koju je javni zaslon pisao. Zaslon nije znao za štrajk; vidio je samo da vozila nema.',
    forWhom: 'Za građane, radnike ZET-a i Holdinga, Grad i novinare: četiri pitanja, četiri ulaza u snimku.',
    q1: 'Što sam mogao umjesto tramvaja?',
    q2: 'Koliko je štrajk bio potpun?',
    q3: 'Što je grad mogao znati u svakoj minuti?',
    q4: 'Odakle brojevi i kako ih provjeriti?',
  },
  questions: {
    label: 'Ulazi u snimku',
    goes: 'Otvara poglavlje {chapter}; odgovor je u odjeljku {section}.',
    section: 'Odgovor u odjeljku',
  },
  numbers: {
    title: 'U brojkama',
    lede: 'Pet brojeva iz snimke; kako je svaki izračunan piše pod Što se vidjelo.',
  },
  kpi: {
    silent: 'sati gotovo bez vozila',
    silentSub: 'od {from} do {to}',
    /** The Monday tile's label after its figure, by Croatian plural (one, few, many). */
    peak: ['vozilo u ponedjeljak u 07:45', 'vozila u ponedjeljak u 07:45', 'vozila u ponedjeljak u 07:45'],
    peakSub: 'običan četvrtak u isto doba: {normal}',
    /** New for the read-through (lane V5): the Monday tile's line against the weekday-matched normal day (decision S-12). */
    peakDaySub: '{day}, običan dan u isto doba: {normal}',
    bikes: 'praznih stanica BAJS-a od {stations}',
    bikesSub: 'najviše {day} u {time}; bicikala sa {from} na {to}',
    return: 'minuta povratka',
    returnSub: 'srijeda, od {from} do {to}',
    alerts: 'upozorenja u ZET-ovim podacima',
    alertsSub: '{alerts} upozorenja i {cancelled} otkazanih vožnji u {hours} sati snimke',
  },
  stage: {
    /** New for the read-through: the stage section's heading (the brief names no string for it). */
    title: 'Grad na jednom satu',
    lede: 'Karta, stanje usluge, glasovi i poglavlja na istom satu. Pusti da snimka pripovijeda ili klikni na bilo što: stavku, poglavlje, liniju.',
    mapLabel: 'Karta grada sa snimljenim vozilima',
    laganoNote: 'Lagani prikaz je bez karte; tijek, zaslon i naslovi su ispod.',
    reducedNote: 'Smanjeno kretanje je uključeno: snimka se ne pokreće sama.',
    scrubber: 'Trenutak snimke',
    valueText: '{day} u {time}',
    paused: 'Zaustavljeno: {day} u {time}.',
    playing: 'Snimka teče, {speed}.',
    end: 'Kraj snimke: {day} u {time}.',
  },
  controls: {
    play: 'Pokreni',
    pause: 'Zaustavi',
    prev: 'Prethodno poglavlje',
    next: 'Sljedeće poglavlje',
    chapters: 'Poglavlja',
    speed: 'Brzina',
  },
  speed: {
    1: 'stvarno vrijeme',
    60: '1 min/s',
    600: '10 min/s',
    3600: '1 h/s',
  } satisfies Record<Speed, string>,
  speedAria: {
    1: 'u stvarnom vremenu',
    60: 'minuta snimke u sekundi',
    600: 'deset minuta snimke u sekundi',
    3600: 'sat snimke u sekundi',
  } satisfies Record<Speed, string>,
  panel: {
    map: 'Karta',
    state: 'Stanje',
    vehicles: 'Vozila',
    lines: 'Linije',
    network: 'Mreža',
    bikes: 'Bicikli',
    weather: 'Vrijeme',
    voices: 'Glasovi',
    agenda: 'Poglavlja',
    screen: 'Zaslon',
    open: 'Otvoreni podaci',
    expand: 'Otvori detalje',
    collapse: 'Zatvori',
    back: 'Natrag na pregled',
    deeper: 'Dalje u dosjeu',
    expanded: '{title}, otvoreno',
    deckLabel: 'Ploče',
  },
  readout: {
    moving: 'u pokretu',
    normal: 'običan dan',
    expected: 'po voznom redu',
    bikesForms: ['bicikl', 'bicikla', 'bicikala'],
    emptyForms: ['prazna stanica', 'prazne stanice', 'praznih stanica'],
    weather: '{temp} °C, {words}',
    weatherTempOnly: '{temp} °C',
    weatherNone: 'bez podatka DHMZ-a',
    dataPath: 'ZET šalje {entities}, u spremištu {depot}, parkirano {parked}, u pokretu {seen}, zaslon je rekao {published}',
    linesCount: '{alive} od {scheduled} linija po voznom redu ima vozilo',
    label: 'Brojke u ovom trenutku',
    // New for the read-through (lane V3): the state rules in words (worker/twin/service.ts), the rail sentence of
    // the Stanje depth, the depths' titles and their two states.
    rules: {
      title: 'Kako aplikacija određuje stanje',
      reduced: 'Smanjeno: u pokretu je manje od polovice vozila po voznom redu, ili su tramvaji ili autobusi zasebno ispod 40 % svojega voznog reda, pet minuta zaredom.',
      silent: 'Gotovo bez vozila: u pokretu su najviše dva vozila ili desetina voznog reda, deset minuta zaredom.',
      lift: 'Iz stanja gotovo bez vozila izlazi se kad je u pokretu barem četvrtina voznog reda tri minute zaredom.',
      normal: 'Uobičajeno: barem 70 % voznog reda, a tramvaji i autobusi svaki barem 60 % svojega, pet minuta zaredom.',
      hold: 'Bez procjene: kad je po voznom redu manje od 20 vozila ili kad ZET-ovi podaci stoje.',
    },
    rail: 'Vlakova nema na karti: snimka bilježi ZET-ova vozila. Na zaslonu se vlak pojavio s nadogradnjom od 29. rujna.',
    dataPathTitle: 'Od ZET-ovih podataka do zaslona',
    vehicles: 'Vozila u pokretu i po voznom redu',
    stations: 'Stanice od najpraznije, u ovom trenutku',
    stationsBikes: 'Bicikala',
    stationsCapacity: 'Mjesta',
    weatherSource: 'DHMZ, Zagreb-Maksimir, po satu',
    loading: 'Učitava se.',
    failed: 'Ovaj se dio snimke trenutačno ne može učitati.',
  },
  layers: {
    label: 'Slojevi',
    vehicles: 'Vozila',
    compare: 'Običan dan',
    bikes: 'BAJS',
    closures: 'Zatvorene ulice',
    noVehiclesAtSpeed: 'Pri brzini od sata u sekundi crtaju se linije s vozilima i bez njih, ne pojedina vozila.',
    compareNote: 'Običan dan je četvrtak 24. rujna u isto doba dana.',
    sources: 'Izvori',
    derived: 'Kaj ima? izvodi',
    live: 'Živa mreža',
    follow: 'Karta prati snimku',
    liveNote: 'Linija svijetli dok je na njoj u zadnjih 15 minuta bilo vozilo; siva je linija po voznom redu bez vozila; tanka je linija izvan voznog reda.',
    compareWhich: 'Običan dan je {day} u isto doba dana.',
    compareLegend: 'Običan dan: položaji vozila kao prazni krugovi',
  },
  legend: {
    alive: 'linija s vozilom',
    dead: 'po voznom redu, bez vozila',
    quiet: 'izvan voznog reda',
    ghost: 'običan dan, položaj vozila',
  },
  twins: {
    title: 'Dvije mreže u istom trenutku',
    now: 'sada',
    normal: '{day} u isto doba',
    count: '{alive} od {scheduled} linija s vozilom',
  },
  timeline: {
    label: 'Vremenska crta snimke',
    chapters: 'Poglavlja',
    notices: 'Obavijesti i presude',
    press: 'Mediji',
    chapterList: 'Popis poglavlja',
    goTo: 'Idi na: {title}',
  },
  director: {
    note: 'Dok snimka teče, karta sama prelazi na mjesto događaja. Pomakni kartu ili odaberi liniju i vodstvo staje; vraća se sljedećim poglavljem ili ovom tipkom.',
    resume: 'Vrati vođeni prikaz',
  },
  subject: {
    label: 'Tema',
    line: 'Linija {short}',
    station: 'Stanica {name}',
    stop: 'Stajalište {name}',
    city: 'cijeli grad',
    now: 'u pokretu sada {seen}, po voznom redu {expected}',
    mini: 'Vozila na liniji kroz snimku',
    headlines: 'Naslovi koji spominju liniju',
    noHeadlines: 'Nijedan naslov ne spominje ovu liniju.',
    bikesNow: 'bicikala sada {n} od {capacity} mjesta',
    clear: 'Ukloni temu',
    hint: 'Dodirni liniju ili stanicu na karti, ili redak u tablici linija.',
  },
  present: {
    enter: 'Cijeli zaslon',
    exit: 'Izađi iz cijelog zaslona',
    hint: 'Tipka F uključuje cijeli zaslon, Escape ga isključuje; upravljanje se skriva nakon tri sekunde mirovanja.',
    unsupported: 'Preglednik ne podržava cijeli zaslon.',
  },
  subtitle: {
    label: 'Rečenica zaslona',
    observed: 'Zaslon je rekao',
    replayed: 'Zaslon bi rekao',
    markObserved: 'Zapis',
    markReplayed: 'Današnja pravila',
    observedNote: 'Zapis javnog zaslona na Trgu bana J. Jelačića u toj minuti.',
    replayedNote: 'Rečenica koju bi današnja pravila aplikacije dala iz podataka te minute; izračunana naknadno.',
    none: 'Za ovu minutu nema rečenice.',
  },
  voices: {
    title: 'Glasovi',
    lede: 'ZET, sud, mediji i sama aplikacija, redom kako su se oglašavali.',
    empty: 'Još se nitko nije oglasio.',
    older: 'Starije',
    kind: {
      zet: 'ZET',
      court: 'Sud',
      press: 'Mediji',
      companion: 'Aplikacija',
      event: 'Snimka',
    },
    atThatMinute: 'U toj minuti',
    atPublish: 'U minuti objave',
    seek: 'Premjesti snimku na {time}',
    more: '{count} naslova iste teme',
    /** New for the read-through (lane V4): voices.more by Croatian plural (one, few, many). */
    moreForms: ['{count} naslov iste teme', '{count} naslova iste teme', '{count} naslova iste teme'],
    showAll: 'Prikaži sve',
    filtered: 'Tema: {subject}',
    hidden: '{count} stavki bez te teme',
    /** New for the read-through (lane V4): voices.hidden by Croatian plural (one, few, many). */
    hiddenForms: ['{count} stavka bez te teme', '{count} stavke bez te teme', '{count} stavki bez te teme'],
    clear: 'Sve teme',
    beat: {
      najava: 'Najava',
      pocetak: 'Početak',
      'prvo-jutro': 'Prvo jutro',
      'jedan-tramvaj': 'Jedan tramvaj',
      'linija-228': 'Linija 228',
      'sud-privremeno': 'Sud, privremeno',
      presuda: 'Presuda',
      povratak: 'Povratak',
      bajs: 'BAJS',
      taksi: 'Taksi',
      volonteri: 'Volonteri',
      skole: 'Škole',
      'drugi-dan': 'Drugi dan',
      'treci-dan': 'Treći dan',
      holding: 'Holding',
      guzve: 'Gužve',
      pregovori: 'Pregovori',
      vlak: 'Vlak',
      nakon: 'Nakon',
    },
  },
  facts: {
    seen: 'u pokretu {n}',
    expected: 'po voznom redu oko {n}',
    state: 'stanje: {state}',
    bikes: 'bicikala {n}',
    bikesEmpty: 'praznih stanica {n}',
    closures: 'zatvorenih ulica {n}',
    temp: '{n} °C',
    feedEmpty: 'ZET bez vozila',
    feedFrozen: 'ZET-ovi podaci stoje',
    route: 'linija {route}: {seen} od {expected}',
    routeNone: 'linija {route}: nijedno vozilo',
    station: '{name}: {bikes}',
    stationEmpty: '{name}: prazna',
    none: 'bez podatka',
  },
  agenda: {
    title: 'Poglavlja',
    lede: 'Koraci snimke; svaki vodi na svoj trenutak.',
    current: 'Trenutno poglavlje',
    open: 'Otvori poglavlje',
    keys: 'Strelice biraju poglavlje, Enter ga otvara.',
  },
  badge: {
    label: 'Stanje usluge',
    normal: 'Uobičajeno',
    reduced: 'Smanjeno',
    silent: 'Gotovo bez vozila',
    unknown: 'Nepoznato',
    loading: 'Učitavanje snimke',
    missing: 'Bez snimke',
    counts: 'u pokretu {seen}, po voznom redu oko {expected}',
    countsNoExpected: 'u pokretu {seen}',
    holds: 'traje {duration}',
    retroShort: 'naknadno',
    retroNote: 'Aplikacija objavljuje stanje usluge od {liveFrom}; ranije je stanje izračunano naknadno, istim pravilima, iz snimljenih podataka.',
  },
  feed: {
    frozen: 'ZET-ovi podaci nisu se mijenjali od {time}.',
    empty: 'ZET šalje podatke bez ijednog vozila.',
  },
  zet: {
    title: 'ZET javlja',
    none: 'Još nema obavijesti.',
    source: 'Izvor: ZET',
  },
  news: {
    title: 'Iz medija',
    none: 'U zadnja tri sata nema odabranog naslova.',
    meta: '{outlet} · {time}',
    newTab: '(otvara se u novoj kartici)',
  },
  marker: {
    title: 'Događaj',
  },
  screen: {
    title: 'Što je zaslon rekao i što bi rekao',
    lede: 'Javni zaslon na Trgu bana J. Jelačića: zapis svakih 20 sekundi gdje postoji i rečenica današnjih pravila za svaku minutu.',
    nearby: 'U blizini',
    place: 'Trg bana J. Jelačića',
    boardNote: 'Između zapisa zaslona: sljedeći polasci s Trga bana J. Jelačića iz voznog reda koji je aplikacija tada imala.',
    captureCaption: 'Snimka zaslona, {day} u {time}',
    noCapture: 'Za ovo doba nema snimke zaslona.',
    quartetTitle: 'Isti zaslon, isti trenutak, pet jutara',
    quartetLede: 'Od ponedjeljka do petka u 07:45: zapis zaslona gdje postoji i rečenica današnjih pravila.',
    quartet: {
      mon: 'Polasci iz voznog reda, izrečeni kao činjenica.',
      tue: 'Isto, dok se ZET-ovi podaci ne mijenjaju.',
      wed: 'Odstupanje izrečeno brojkama.',
      thu: 'Uobičajeno jutro.',
      fri: 'Drugo uobičajeno jutro.',
    },
    // New for the read-through (lane S3): the miniature's name, the board between runs without departures.
    miniLabel: 'Umanjeni prikaz javnog zaslona',
    boardNone: 'U voznom redu nema sljedećih polazaka.',
    sourceLabel: 'Izvor rečenice',
    sourceObserved: 'Zapis',
    sourceReplayed: 'Današnja pravila',
    replayedNote: 'Današnja pravila primijenjena naknadno na podatke te minute: ovako bi zaslon govorio da je nadogradnja od 29. rujna bila ugrađena od početka.',
    noReplayed: 'Za ovu minutu nema izračunane rečenice.',
  },
  strip: {
    title: 'Tijek',
    lede: 'Gotovo pet dana na jednoj osi. Crta prati sat; klik ili povlačenje premješta snimku.',
    fleet: 'Vozila u pokretu',
    fleetSeen: 'u pokretu',
    fleetExpected: 'po voznom redu',
    fleetCompare: 'običan dan',
    state: 'Stanje usluge',
    stateRetro: 'izračunano naknadno',
    stateNone: 'bez procjene',
    bikes: 'Bicikli na stanicama',
    bikesEmpty: 'Prazne stanice',
    feed: 'ZET-ovi podaci',
    feedEmpty: 'bez vozila',
    feedFrozen: 'ne mijenjaju se',
    feedDepot: 'u spremištu',
    feedFuture: 'vrijeme unaprijed',
    product: 'Broj na zaslonu i stvarni broj',
    productScreen: 'zaslon je rekao',
    productFeed: 'vozila s položajem',
    news: 'Medijski naslovi po satu',
    readout: '{day} u {time}: {values}',
    table: 'Brojevi po satu',
    noValue: 'bez podatka',
    // New for the read-through (lane S3, after the integration review): the ghosts panel that replaces the two lines.
    ghosts: 'Vozila koja je zaslon brojio, a nisu imala položaj',
    // New for the read-through (lane S3): the plots' name, the first column of every table.
    plotsLabel: 'Tijek na jednoj osi; strelice lijevo i desno pomiču snimku za deset minuta, sa Shiftom za sat.',
    hour: 'Sat',
    lines: 'Sve linije, svaki sat',
    linesLede: 'Udio vozila prema voznom redu po liniji i satu: tramvaji pa autobusi.',
    linesRatio: 'udio prema voznom redu',
    linesOtherBuses: 'Ostale autobusne linije ({n}), zajedno',
    linesAll: 'Prikaži sve autobusne linije',
    linesCell: 'linija {short}, {day} u {hour}: {seen} od {expected}',
    linesNone: 'ne vozi po voznom redu',
    tram: 'Tramvaji',
    bus: 'Autobusi',
    weather: 'Temperatura i vrijeme',
  },
  // New for the read-through (lane V3): the heatmap's ramp words, its blank cell and its table's first column.
  heatmap: {
    ramp: ['nijedno vozilo', 'do četvrtine', 'do polovice', 'do tri četvrtine', 'puni vozni red'],
    missing: 'bez podatka',
    route: 'Linija',
  },
  alternatives: {
    title: 'Što je ostalo kad tramvaja nije bilo',
    lede: 'Bicikli, vlakovi, jedna autobusna linija i ono što su mediji zabilježili. Sve iz snimke, s izvorom.',
    bikes: 'Stanice BAJS-a koje su se prve ispraznile',
    bikesMethod: 'Za svaku stanicu prva minuta ponedjeljka nakon 05:00 u kojoj je broj bicikala pao na nulu, iz podataka nextbikea svakih pet minuta; prvih deset.',
    station: 'Stanica',
    emptyFrom: 'Prazna od',
    bikesAtFive: 'Bicikala u 05:00',
    showOnMap: 'Pokaži na karti',
    rail: 'Vlak u zaglavlju zaslona',
    railMethod: 'Rečenice zaglavlja o vlaku po danu, iz zapisa zaslona. Vlakovi su se na zaslonu pojavili s nadogradnjom od 29. rujna; snimka ne govori o prometu vlakova, samo o zaslonu.',
    railValue: '{count} rečenica o vlaku',
    line228: 'Autobusna linija 228 do Rebra',
    line228Method: 'Vozila linije 228 u pokretu po satu od utorka 29. rujna, iz snimljenih položaja po liniji; obavijest ZET-a 10166.',
    press: 'Što su mediji zabilježili',
    pressLede: 'Taksi, volonteri, škole i gužve: naslovi s poveznicom na izvorni članak.',
    // New for the read-through (lane V5): a row button's name ("Pokaži na karti: Stanica 3"), line 228's table twin
    // and readout, and the empty states.
    showOnMapNamed: '{action}: {name}',
    line228Hour: 'Sat',
    line228Seen: 'najviše vozila u pokretu',
    line228Expected: 'po voznom redu',
    line228Value: '{n} u pokretu',
    line228Summary: 'Najviše {n} vozila linije 228 u pokretu u jednom satu.',
    line228Notice: 'Obavijest ZET-a 10166',
    railNone: 'U zapisima zaslona nema rečenice o vlaku.',
    bikesNone: 'U ponedjeljak se nijedna stanica nije ispraznila nakon 05:00.',
    pressNone: 'Za ove teme nema odabranog naslova.',
    pressMeta: '{outlet} · {time}',
  },
  reckoning: {
    title: 'Što se vidjelo',
    lede: 'Brojevi izračunati iz ove snimke. Ispod svakog piše kako.',
    silent: 'Koliko dugo gotovo bez vozila',
    silentMethod: 'Minute u stanju „gotovo bez vozila”, zbrojene po danima, iz stanja usluge izračunanog nad snimljenim podacima.',
    peak: 'Pet jutara u 07:45',
    peakMethod: 'Vozila u pokretu u 07:45 svakog dana i običnog četvrtka 24. rujna u isto doba.',
    bikes: 'Bicikli kao zamjena',
    bikesMethod: 'Najmanji zbroj bicikala i najveći broj praznih stanica po danu, iz podataka nextbikea svake minute.',
    ghosts: 'Broj koji nije bio točan',
    ghostsLede: 'U ponedjeljak je zaslon cijeli dan brojio više vozila nego što ih je imalo položaj: dva tramvaja kojima je ZET u ponoć upisao vrijeme dan unaprijed i vozila bez položaja.',
    ghostsMethod: 'Razlika između broja koji je aplikacija objavila i broja vozila s položajem u ZET-ovim podacima, po minutama. Broje se samo minute u kojima je manje od 20 vozila u pokretu već više od deset minuta zaredom, uz barem dva viška ili uz objavljen broj kad nijedno vozilo nema položaj: dok se vozni park smanjuje ili raste, razlika su vozila koja su se tek prestala javljati.',
    return: 'Povratak',
    returnMethod: 'Od prve minute s najmanje deset vozila u pokretu u srijedu navečer do prve minute uobičajenog stanja.',
    feed: 'ZET-ovi podaci',
    feedMethod: 'Minute u kojima ZET nije slao nijedno vozilo i minute u kojima se ZET-ovi podaci nisu mijenjali.',
    sentences: 'Što je zaslon govorio',
    sentencesMethod: 'Rečenice zaglavlja po vrsti, iz zapisa zaslona svakih 20 sekundi.',
    lines: 'Linije s vozilom u pokretu',
    linesMethod: 'Linije s barem jednim vozilom u pokretu u bilo kojem petominutnom razmaku dana, iz snimljenih položaja po liniji.',
    linesValue: '{count} od {total} linija',
    alerts: 'Što je ZET rekao u podacima',
    alertsMethod: 'Upozorenja i otkazane vožnje u ZET-ovim podacima u stvarnom vremenu, zbrojeni po minutama snimke.',
    alertsValue: '{alerts} upozorenja, {cancelled} otkazanih vožnji',
    // New for the read-through (lane S3): the labels inside the cards.
    total: 'ukupno',
    span: 'od {from} do {to}',
    none: 'U snimci nema takvih minuta.',
    peakCompare: 'čet 24. 9., običan dan',
    day: 'Dan',
    bikesMin: 'najmanje bicikala',
    bikesEmptyMax: 'najviše praznih stanica',
    ghostsMax: 'Najveća razlika',
    ghostsMaxValue: '{count} više nego s položajem, {day} u {time}',
    ghostsMinutes: 'Minute s razlikom',
    returnFrom: 'Prvih deset vozila u pokretu',
    returnTo: 'Prva minuta uobičajenog stanja',
    feedEmpty: 'ZET ne šalje nijedno vozilo',
    feedFrozen: 'ZET-ovi podaci se ne mijenjaju',
    feedLongest: 'najdulje {duration}, od {from}',
    liveRows: 'Redovi s polaskom uživo',
    liveRowsValue: '{live} od {rows} redova s polaskom',
    // New for the read-through (lane V5): the peak card with five mornings and two normal days, the lines card's
    // Monday row and the bikes card's figure.
    peakFive: 'Jutra u 07:45',
    peakFiveMethod: 'Vozila u pokretu u 07:45 svakog jutra snimke i dvaju običnih dana u isto doba: ponedjeljka 21. i četvrtka 24. rujna.',
    normalDay: '{day}, običan dan',
    linesMonday: 'U ponedjeljak 28. rujna',
    linesNone: 'nijedna',
    bikesDrained: 'bicikala manje na stanicama, od najvećeg zbroja do najmanjeg',
    families: {
      'departure-timetable': 'Polazak po voznom redu',
      'departure-live': 'Polazak uživo',
      'first-last': 'Prvi ili zadnji polazak',
      service: 'Stanje usluge',
      outage: 'Bez ZET-ovih podataka',
      rail: 'Vlak',
      bikes: 'Bicikli',
      closure: 'Zatvorena ulica',
      event: 'Događanje',
      weather: 'Vrijeme',
      solar: 'Izlazak ili zalazak sunca',
      notice: 'Obavijest ZET-a',
      other: 'Ostalo',
    },
  },
  open: {
    title: 'Otvoreni podaci iz snimke',
    lede: 'Podaci koje Grad nije imao, a aplikacija ih je izvela iz otvorenih izvora. Svaki je preuzimljiv, s izvorom, licencom i načinom izračuna.',
    signal: 'Podatak',
    signalSource: 'Iz čega',
    signalCadence: 'Korak',
    signalUse: 'Kome koristi',
    row: {
      state: 'Stanje usluge po minuti',
      stateUse: 'Gradu i ZET-u: kad je promet odstupao i koliko',
      fleet: 'Vozila u pokretu i po voznom redu, po liniji',
      fleetUse: 'ZET-u i medijima: koje su linije vozile',
      feed: 'Pouzdanost ZET-ovih podataka: prazni i zamrznuti okviri, vremena iz budućnosti, upozorenja',
      feedUse: 'ZET-u i timu za otvorene podatke',
      bikes: 'Bicikli po stanici svakih pet minuta',
      bikesUse: 'Gradu i nextbikeu: gdje je zamjena nestala prva',
      closures: 'Zatvorene ulice po inačici skupa, s pomicanjem kraja',
      closuresUse: 'Gradu: koji krajevi radova nisu stvarni',
      voice: 'Rečenice zaslona, zapisane i izračunane',
      voiceUse: 'Svima: što je grad mogao pročitati',
    },
    cadence: {
      minute: 'svaku minutu',
      five: 'svakih pet minuta',
      change: 'pri svakoj promjeni',
    },
    source: {
      zet: 'ZET, GTFS-RT',
      nextbike: 'nextbike, GBFS',
      city: 'Grad Zagreb, data.zagreb.hr',
      kajima: 'Kaj ima?',
    },
    downloads: 'Preuzimanja',
    download: '{title} ({format}, {size})',
    rows: '{rows} redaka',
    licence: 'Otvorena dozvola, uz navođenje izvora',
    catalog: 'Skup je u katalogu /open/catalog.json (DCAT-AP).',
    catalogLink: 'Katalog otvorenih podataka',
    repro: 'Ponovljivost',
    reproText: 'Skup je izgrađen iz snimki naredbom npm run build:snimka na predaji {commit}; ugovor podataka i opis cjevovoda su u docs/snimka-2026-10.md, a sažetak svake datoteke u manifestu.',
    promise: 'Prijava Gradu obećava otvorene podatke u oba smjera: Grad daje, a Kaj ima? vraća ono što izvede. Ovo je prvi takav skup.',
    notIncluded: 'Nisu u preuzimanjima: naslovi medija i tekst ZET-ovih obavijesti (samo poveznice), sirovi ZET-ovi okviri (nikad) i bilo koja brojka o ljudima (nema ih).',
    // New for the read-through (lane V5): a download's stable link (the catalogue's alias), the forms of "{rows} redaka",
    // the catalogue entry, the pipeline brief and the commit link.
    latest: 'Stalna poveznica',
    latestNamed: 'Stalna poveznica: {title}',
    rowForms: ['redak', 'retka', 'redaka'],
    catalogEntry: 'Skup u popisu otvorenih podataka',
    brief: 'Opis cjevovoda',
    commit: 'Predaja {commit}',
  },
  live: {
    title: 'I danas',
    kicker: 'Uživo, nije snimka',
    lede: 'Isti podatak koji je snimka pratila tri dana, sada.',
    now: 'Sada: u pokretu {seen}, po voznom redu oko {expected}, stanje {state}.',
    age: 'Podatak star {age}.',
    unavailable: 'Trenutačno stanje nije dostupno.',
    app: 'Otvori aplikaciju',
    stats: 'Statistika',
    method: 'Jedno čitanje javnog sažetka aplikacije kad se ova kartica pojavi; ništa se ne broji i ne šalje.',
  },
  sources: {
    title: 'Izvori i zasluge',
    zet: 'Položaji vozila: ZET, javni GTFS-RT, izvedeni modelom kretanja aplikacije iz snimljenih podataka; sirovi podaci ZET-a ovdje se ne objavljuju. Obavijesti ZET-a: zet.hr.',
    nextbike: 'Bicikli: nextbike (BAJS), GBFS, CC0 1.0.',
    city: 'Zatvorene ulice: Grad Zagreb, data.zagreb.hr, Otvorena dozvola.',
    dhmz: 'Temperatura i vrijeme: DHMZ, postaja Zagreb-Maksimir, Otvorena dozvola.',
    news: 'Naslovi: Jutarnji list, Večernji list i N1. Svaki naslov vodi na izvorni članak; ovdje se prenose samo naslovi.',
    court: 'Presude: Županijski sud u Zagrebu, 30. rujna 2026., prema izvještajima medija i obavijesti ZET-a.',
    strike: 'Riječ štrajk stoji samo u tekstu ove stranice. Zaslon u snimci nikada je ne ispisuje: aplikacija zna stanje voznog parka, ne i njegov uzrok.',
    map: 'Karta: © OpenStreetMap contributors · Protomaps.',
    live: 'Kartica „I danas” jedina na stranici čita živi izvor: javni sažetak aplikacije, jednom, kad se pojavi na zaslonu.',
    open: 'Preuzimanja: izvedeni skupovi pod Otvorenom dozvolom, uz navođenje izvora; ZET-ova atribucija doslovno.',
    voice: 'Rečenice „zaslon bi rekao” izračunane su naknadno današnjim pravilima aplikacije i tako su označene; zapis zaslona je ono što je doista pisalo.',
    dataset: 'Opis skupa podataka',
    statistika: 'Statistika',
    prijava: 'Prijava projekta',
    catalog: 'Otvoreni podaci',
  },
  size: {
    kb: '{n} KB',
    mb: '{n} MB',
  },
  error: {
    load: 'Snimka se trenutačno ne može učitati.',
    retry: 'Pokušaj ponovno',
  },
  noscript: 'Snimka treba JavaScript. Izvori i opis skupa podataka nalaze se ispod.',
  // New for the read-through (the brief has no string for these):
  time: {
    /** duration() under one minute, where "0 min" would read as a count. */
    underMinute: 'manje od minute',
  },
  attribution: {
    /** The heading over the manifest's footnotes (gaps and caveats) under the attribution list. */
    notes: 'Napomene uz snimku',
  },
} as const;

export type SnimkaStrings = typeof SN;

// In tests and in development a placeholder nobody filled is a bug worth a throw; in production
// the text goes out as it is, a brace being better than a blank page.
const STRICT = ((): boolean => {
  try { return import.meta.env.MODE === 'test' || Boolean(import.meta.env.DEV); } catch { return false; }
})();

/** Replaces every `{name}` of `vars` in the template, as fill() in app/src/kiosk/strings.ts does. */
export function fill(template: string, vars: Record<string, string | number>): string {
  let out = template;
  for (const [key, value] of Object.entries(vars)) out = out.split(`{${key}}`).join(String(value));
  if (STRICT) {
    const left = /\{([A-Za-z]+)\}/.exec(out);
    if (left) throw new Error(`snimka strings: placeholder {${left[1]}} left unfilled in "${template}"`);
  }
  return out;
}

/** Every leaf of SN with its dot path, for the guards; an array of forms counts as one leaf per form. */
export function leaves(node: unknown = SN, prefix = ''): [key: string, text: string][] {
  if (typeof node === 'string') return [[prefix, node]];
  if (Array.isArray(node)) return node.flatMap((v, i) => leaves(v, `${prefix}.${i}`));
  if (node && typeof node === 'object') {
    return Object.entries(node as Record<string, unknown>).flatMap(([k, v]) => leaves(v, prefix ? `${prefix}.${k}` : k));
  }
  return [];
}
