// English kiosk copy. Keys are typed by KioskStrings (strings.ts).
import type { KioskStrings } from './strings';

export const en: KioskStrings = {
  appName: 'Kaj ima?',
  surface: 'public screen',
  languageName: 'English',
  header: {
    context: '{stop} · {district}',
    clockLabel: 'Clock',
    sessionLabel: 'Session',
    driver: 'The person who scanned drives the screen',
    temporaryUntil: 'temporary screen · valid until {time}',
    venue: 'venue screen',
    unlockedUntil: 'Unlocked until {time}',
  },
  status: {
    connecting: 'Connecting to the screen…',
    offline: 'Screen offline — no code can be issued',
    reconnecting: 'Reconnecting…',
    dataDown: 'The screen overview could not refresh.',
    dataStale: 'Data is stale',
    lightweight: 'light mode',
  },
  invitation: {
    lead: 'Scan for 10 minutes of the city.',
    support: 'Transit, weather, events and safety on your phone. No account, nothing to install.',
    typeCode: 'or type the code at {host}',
    codeLabel: 'Unlock code',
    qrLabel: 'QR code to unlock. Code: {code}',
    qrWaiting: 'Code on its way…',
    codeWaiting: 'waiting for a code',
    codeValid: 'Code valid for {seconds} s',
    progressLabel: 'Time left on this code',
  },
  weather: {
    title: 'Weather now',
    humidity: 'humidity {value} %',
    wind: 'wind {dir} {speed} m/s',
    windCalm: 'calm',
    windNoDir: 'wind {speed} m/s',
    compass: { N: 'north', NE: 'northeast', E: 'east', SE: 'southeast', S: 'south', SW: 'southwest', W: 'west', NW: 'northwest' },
    pressure: '{value} hPa',
    observed: 'observed {time}',
    sunrise: 'sunrise {time}',
    sunset: 'sunset {time}',
    daylight: 'daylight {hours} h {minutes} min',
    range: '{min} to {max} °C',
    unavailable: 'DHMZ data is unavailable right now.',
    loading: 'Loading DHMZ data…',
    station: 'station {name}',
    noReading: 'no temperature reading',
  },
  lines: {
    title: 'Lines from this stop',
    nearbyTitle: 'Lines nearby',
    tram: 'tram',
    bus: 'bus',
    nearby: { one: '{count} vehicle nearby', other: '{count} vehicles nearby' },
    noneNearby: 'no vehicle nearby',
    more: { one: '{count} more line', other: '{count} more lines' },
    unavailable: 'ZET is not answering right now.',
    loading: 'Loading ZET data…',
    noStop: 'This screen has no stop selected.',
    modelNote: 'Vehicle positions are estimates from ZET reports; a line’s delay is not an arrival time.',
    vehiclesMoving: { one: '{count} vehicle moving', other: '{count} vehicles moving' },
  },
  story: {
    city: 'From the city',
    assembly: 'City Assembly',
    zet: 'ZET notice',
    neighbourhood: 'Neighbourhood news',
    works: 'Municipal works',
    news: 'HRT news',
    quake: 'Latest earthquake',
    published: 'published {time}',
    changed: 'last changed {date}',
    quakeBody: 'Magnitude {mag} · {region} · depth {depth} km',
    empty: 'No new notices right now.',
  },
  safety: {
    label: 'Safety',
    warningsNone: 'No DHMZ warnings for Zagreb',
    warningsUnknown: 'DHMZ warnings: data unavailable right now',
    warningsStale: 'DHMZ warnings: stale, unconfirmed',
    warningsUpcoming: 'Announced from {time}: {severity} · {title}',
    warningsLoading: 'DHMZ warnings: loading',
    closuresUnknown: 'Closures: data unavailable right now',
    closuresStale: 'Closures: stale, unconfirmed',
    closuresNearest: 'nearest {street}',
    pharmacy: 'On-duty pharmacy',
    hitno: 'Safety',
    basics: 'Essentials',
  },
  basics: {
    title: 'Essentials, no scan needed',
    hint: 'This screen answers even without a phone. Scanning unlocks the whole city on your own device.',
    close: 'Back',
    empty: 'The source is not answering right now. The safety layer runs at /hitno.',
    routes: 'Lines nearby',
    weather: 'Weather now',
    pharmacy: 'On-duty pharmacy',
    warnings: 'Warnings',
    closures: 'Road closures',
  },
  session: {
    join: 'Join',
    joinHint: 'Scan for the same view on your phone',
    selected: 'Selected on the phone',
    selectedRoute: 'Line {route}',
    selectedStop: 'Stop {stop}',
    ended: 'The session has ended.',
  },
  layers: {
    'grad-sada': 'Now',
    'u-pokretu': 'Transit',
    'zrak-i-nebo': 'Weather',
    sigurnost: 'Safety',
    'uprava-i-pravo': 'City',
    kultura: 'Events',
    vijesti: 'News',
  },
  events: {
    izvedba: 'performance',
    koncert: 'concert',
    izlozba: 'exhibition',
    film: 'film',
    radionica: 'workshop',
    predavanje: 'lecture',
    razgovor: 'talk',
    festival: 'festival',
    sajam: 'fair',
    predstavljanje: 'presentation',
    program: 'programme',
    diskurzivno: 'talks and lectures',
    muzika: 'music',
    dogadjanje: 'event',
    'sjednica-skupstine': 'Assembly session',
    'sjednica-odbora': 'committee session',
  },
  paired: {
    warnings: 'DHMZ warnings',
    closures: 'Road closures',
    delays: 'Delays by line',
    quakes: 'Earthquakes within 150 km, 72 h',
    today: 'Today',
    tomorrow: 'Tomorrow',
    later: 'Coming days',
    forecast: 'Forecast for today',
    sun: 'Sun',
    pharmacies: 'On-duty pharmacies',
    assemblyPoints: 'Civil protection assembly points',
    acts: 'Official Gazette',
    sessions: 'Sessions',
    works: 'Municipal works',
    agenda: 'Agenda',
    notices: 'Undated notices',
    ongoing: 'Ongoing',
    ongoingWord: 'ongoing',
    ongoingUntil: 'until {date}',
    zetNotices: 'ZET notices',
    headlines: 'Headlines',
    overviewTransport: 'Transit around the stop',
    allDay: 'all day',
    noData: 'No data',
    sourceDown: 'The source is not answering right now',
    unconfirmed: 'Stale: the source is not answering, state unconfirmed',
    dataFrom: 'data as of {time}',
    fetchedAt: 'retrieved {time}',
    stale: 'stale',
    phase: 'phase: {phase}',
    amount: 'amount €{amount}',
    coverage: 'showing {shown} of {total}',
    coverageLines: { one: 'showing {shown} of {total} line', other: 'showing {shown} of {total} lines' },
    routeVehicles: { one: '{count} vehicle', other: '{count} vehicles' },
    depth: 'depth {depth} km',
    magUnknown: 'magnitude unknown',
    depthUnknown: 'depth unknown',
    upcomingFrom: 'announced from {time}',
    quakeNone: 'No earthquakes recorded in the last 72 hours.',
    warningsNone: 'No warnings for the Zagreb region.',
    closuresNone: 'No closures reported.',
    eventsNone: 'No events announced.',
    newsNone: 'No new headlines.',
    actsNone: 'No new acts.',
    worksNone: 'No works on record.',
    sessionsNone: 'No sessions announced.',
    sunUnknown: 'Sun: not computed',
    rangeUnknown: 'daily range not published',
    untilTime: 'until {time}',
    direction: 'direction: {direction}',
    lineWord: 'line',
    stopWord: 'stop',
    licence: 'Licence',
    sourceLabel: 'Source',
    sourcesLabel: 'Sources',
    fullSources: 'full attribution: /izvori',
  },
  notice: {
    expiredTitle: 'This temporary screen has expired.',
    expiredBody: 'Temporary screens last 24 hours. The screen no longer issues codes; set up a new one to continue.',
    revokedTitle: 'This screen has been switched off.',
    revokedBody: 'The operator revoked the screen and its codes are void. Ask the operator for a new screen, or set up a temporary one.',
    setupAgain: 'Set up a new temporary screen',
    endsAfterSession: 'The open session runs to its end; the screen then stops issuing codes.',
  },
  setup: {
    title: 'Set up a temporary screen',
    intro: 'For evaluation: choose a city district and a stop. The screen lasts 24 hours and uses the same real pairing and data as venue screens.',
    step1: 'Step 1 of 2',
    step2: 'Step 2 of 2',
    districtLegend: 'City district',
    stopLegend: 'Stop',
    search: 'Search stops by name',
    searchHint: 'Stops nearest the district seat are listed; type a name for others.',
    nearest: 'nearest the district seat',
    results: { one: '{count} stop', other: '{count} stops' },
    noResults: 'No stop with that name.',
    routesAt: 'lines {routes}',
    next: 'Next',
    back: 'Back',
    create: 'Create screen',
    creating: 'Creating the screen…',
    summary: '{stop} · {district}',
    validity: 'Valid 24 hours · at most five screens per evaluator per hour',
    errorAccess: 'Setup requires evaluator access (Cloudflare Access). Sign in and try again.',
    errorQuota: 'The hourly limit of temporary screens has been reached.',
    errorNetwork: 'The server is unreachable. Check the connection and try again.',
    errorInvalid: 'The choice was not accepted ({field}). Choose again.',
    errorFailed: 'Creating the screen failed. Try again.',
    errorStops: 'The stop list is unavailable.',
    retry: 'Try again',
    retryIn: 'Try again in {time}',
    loadingStops: 'Loading stops…',
    provisionHint: 'A venue screen receives its provisioning link from the operator; this form creates a temporary evaluation screen.',
  },
};
