// Croatian kiosk copy. Keys are typed by KioskStrings (strings.ts).
import type { KioskStrings } from './strings';

export const hr: KioskStrings = {
  appName: 'Kaj ima?',
  surface: 'javni zaslon',
  languageName: 'Hrvatski',
  header: {
    context: '{stop} · {district}',
    clockLabel: 'Sat',
    sessionLabel: 'Sesija',
    driver: 'Zaslon vodi osoba koja je skenirala',
    temporaryUntil: 'privremeni zaslon · vrijedi do {time}',
    venue: 'zaslon u prostoru',
    unlockedUntil: 'Otključano do {time}',
  },
  status: {
    connecting: 'Povezivanje sa zaslonom…',
    offline: 'Bez veze sa zaslonom — kod se ne može izdati',
    reconnecting: 'Ponovno povezivanje…',
    dataDown: 'Izvor podataka nedostupan',
    dataStale: 'Podaci zastarjeli',
    lightweight: 'lagani način',
  },
  invitation: {
    lead: 'Skeniraj za 10 minuta grada.',
    support: 'Promet, vrijeme, događanja i sigurnost na tvom telefonu. Bez računa i bez instalacije.',
    typeCode: 'ili upiši kod na zagreb.aningfilm.hr/s',
    codeLabel: 'Kod za otključavanje',
    qrLabel: 'QR kod za otključavanje. Kod: {code}',
    qrWaiting: 'Kod stiže…',
    codeWaiting: 'čekanje koda',
    codeValid: 'Kod vrijedi još {seconds} s',
    progressLabel: 'Preostalo vrijeme ovog koda',
  },
  weather: {
    title: 'Vrijeme sada',
    humidity: 'vlaga {value} %',
    wind: 'vjetar {dir} {speed} m/s',
    windCalm: 'bez vjetra',
    windNoDir: 'vjetar {speed} m/s',
    compass: { N: 'sjever', NE: 'sjeveroistok', E: 'istok', SE: 'jugoistok', S: 'jug', SW: 'jugozapad', W: 'zapad', NW: 'sjeverozapad' },
    pressure: '{value} hPa',
    observed: 'opaženo {time}',
    sunrise: 'izlazak {time}',
    sunset: 'zalazak {time}',
    daylight: 'dan traje {hours} h {minutes} min',
    range: '{min} do {max} °C',
    unavailable: 'Podaci DHMZ-a trenutačno nisu dostupni.',
    loading: 'Učitavanje podataka DHMZ-a…',
    station: 'postaja {name}',
  },
  lines: {
    title: 'Linije s ove stanice',
    nearbyTitle: 'Linije u blizini',
    tram: 'tramvaj',
    bus: 'autobus',
    nearby: { one: '{count} vozilo u blizini', few: '{count} vozila u blizini', other: '{count} vozila u blizini' },
    noneNearby: 'nijedno vozilo u blizini',
    more: { one: 'još {count} linija', few: 'još {count} linije', other: 'još {count} linija' },
    unavailable: 'ZET trenutačno ne odgovara.',
    loading: 'Učitavanje podataka ZET-a…',
    noStop: 'Zaslon nema odabranu stanicu.',
    modelNote: 'Položaj vozila je procjena iz očitanja ZET-a; kašnjenje linije nije vrijeme dolaska.',
    vehiclesMoving: { one: '{count} vozilo u pokretu', few: '{count} vozila u pokretu', other: '{count} vozila u pokretu' },
  },
  story: {
    city: 'Grad javlja',
    assembly: 'Gradska skupština',
    zet: 'ZET obavijest',
    neighbourhood: 'Kvartovske novosti',
    works: 'Komunalni radovi',
    news: 'HRT vijesti',
    quake: 'Posljednji potres',
    published: 'objavljeno {time}',
    changed: 'zadnja izmjena {date}',
    quakeBody: 'Magnituda {mag} · {region} · dubina {depth} km',
    empty: 'Trenutačno nema novih obavijesti.',
  },
  safety: {
    label: 'Sigurnost',
    warningsNone: 'Nema upozorenja DHMZ-a za Zagreb',
    warningsUnknown: 'Upozorenja DHMZ-a: podaci trenutačno nedostupni',
    warningsStale: 'Upozorenja DHMZ-a: zastarjelo, stanje nije potvrđeno',
    warningsLoading: 'Upozorenja DHMZ-a: učitavanje',
    closuresUnknown: 'Zatvaranja: podaci trenutačno nedostupni',
    closuresStale: 'Zatvaranja: zastarjelo, stanje nije potvrđeno',
    closuresNearest: 'najbliže {street}',
    pharmacy: 'Dežurna ljekarna',
    hitno: '/hitno',
    basics: 'Osnovno',
  },
  basics: {
    title: 'Osnovno, bez skeniranja',
    hint: 'Ovaj zaslon odgovara i bez telefona. Skeniranje otključava cijeli grad na tvom uređaju.',
    close: 'Natrag',
    empty: 'Izvor trenutačno ne odgovara. Sigurnosni sloj radi na /hitno.',
    routes: 'Linije u blizini',
    weather: 'Vrijeme sada',
    pharmacy: 'Dežurna ljekarna',
    warnings: 'Upozorenja',
    closures: 'Zatvorene prometnice',
  },
  session: {
    join: 'Pridruži se',
    joinHint: 'Skeniraj za isti pregled na svom telefonu',
    selected: 'Odabrano na telefonu',
    selectedRoute: 'Linija {route}',
    selectedStop: 'Stanica {stop}',
    ended: 'Sesija je završila.',
  },
  layers: {
    'grad-sada': 'Sada',
    'u-pokretu': 'Promet',
    'zrak-i-nebo': 'Vrijeme',
    sigurnost: 'Sigurnost',
    'uprava-i-pravo': 'Grad',
    kultura: 'Događanja',
    vijesti: 'Vijesti',
  },
  events: {
    izvedba: 'izvedba',
    koncert: 'koncert',
    izlozba: 'izložba',
    film: 'film',
    radionica: 'radionica',
    predavanje: 'predavanje',
    razgovor: 'razgovor',
    festival: 'festival',
    sajam: 'sajam',
    predstavljanje: 'predstavljanje',
    program: 'program',
    diskurzivno: 'razgovori i predavanja',
    muzika: 'glazba',
    dogadjanje: 'događanje',
    'sjednica-skupstine': 'sjednica Skupštine',
    'sjednica-odbora': 'sjednica odbora',
  },
  paired: {
    warnings: 'Upozorenja DHMZ-a',
    closures: 'Zatvorene prometnice',
    delays: 'Kašnjenja po linijama',
    quakes: 'Potresi u 7 dana',
    today: 'Danas',
    tomorrow: 'Sutra',
    later: 'Sljedećih dana',
    forecast: 'Prognoza za danas',
    sun: 'Sunce',
    pharmacies: 'Dežurne ljekarne',
    assemblyPoints: 'Zborna mjesta civilne zaštite',
    acts: 'Službeni glasnik',
    sessions: 'Sjednice',
    works: 'Komunalni radovi',
    agenda: 'Program',
    notices: 'Obavijesti bez datuma',
    ongoing: 'U tijeku',
    ongoingWord: 'u tijeku',
    ongoingUntil: 'do {date}',
    zetNotices: 'ZET obavijesti',
    headlines: 'Naslovi',
    overviewTransport: 'Promet oko stanice',
    allDay: 'cijeli dan',
    noData: 'Nema podataka',
    sourceDown: 'Izvor trenutačno ne odgovara',
    unconfirmed: 'Zastarjelo: izvor ne odgovara, stanje nije potvrđeno',
    dataFrom: 'podaci od {time}',
    stale: 'zastarjelo',
    phase: 'faza: {phase}',
    amount: 'iznos {amount} €',
    coverage: 'prikazano {shown} od {total}',
    routeVehicles: { one: '{count} vozilo', few: '{count} vozila', other: '{count} vozila' },
    depth: 'dubina {depth} km',
    quakeNone: 'Nema zabilježenih potresa u posljednjih 7 dana.',
    warningsNone: 'Nema upozorenja za Zagrebačku regiju.',
    closuresNone: 'Nema prijavljenih zatvaranja.',
    eventsNone: 'Nema najavljenih događanja.',
    newsNone: 'Nema novih naslova.',
    actsNone: 'Nema novih akata.',
    worksNone: 'Nema evidentiranih radova.',
    sessionsNone: 'Nema najavljenih sjednica.',
    sunUnknown: 'Sunce: nije izračunato',
    rangeUnknown: 'dnevni raspon nije objavljen',
    untilTime: 'do {time}',
    direction: 'smjer: {direction}',
    lineWord: 'linija',
    stopWord: 'stanica',
    licence: 'Licenca',
  },
  notice: {
    expiredTitle: 'Ovaj privremeni zaslon je istekao.',
    expiredBody: 'Privremeni zasloni vrijede 24 sata. Zaslon više ne izdaje kodove; postavi novi da nastaviš.',
    revokedTitle: 'Ovaj je zaslon isključen.',
    revokedBody: 'Operater je opozvao zaslon i kodovi više ne vrijede. Za novi zaslon obrati se operateru ili postavi privremeni.',
    setupAgain: 'Postavi novi privremeni zaslon',
    endsAfterSession: 'Otvorena sesija traje do svog kraja; zaslon zatim prestaje izdavati kodove.',
  },
  setup: {
    title: 'Postavi privremeni zaslon',
    intro: 'Za ocjenjivanje: odaberi gradsku četvrt i stanicu. Zaslon vrijedi 24 sata i koristi ista stvarna uparivanja i podatke kao zasloni u prostorima.',
    step1: 'Korak 1 od 2',
    step2: 'Korak 2 od 2',
    districtLegend: 'Gradska četvrt',
    stopLegend: 'Stanica',
    search: 'Traži stanicu po imenu',
    searchHint: 'Prikazane su stanice najbliže sjedištu četvrti; upiši ime za druge.',
    nearest: 'najbliže sjedištu četvrti',
    results: { one: '{count} stanica', few: '{count} stanice', other: '{count} stanica' },
    noResults: 'Nema stanice s tim imenom.',
    routesAt: 'linije {routes}',
    next: 'Dalje',
    back: 'Natrag',
    create: 'Stvori zaslon',
    creating: 'Stvaranje zaslona…',
    summary: '{stop} · {district}',
    validity: 'Vrijedi 24 sata · najviše pet zaslona po ocjenjivaču na sat',
    errorAccess: 'Postavljanje traži ocjenjivački pristup (Cloudflare Access). Prijavi se pa pokušaj ponovno.',
    errorQuota: 'Dosegnut je broj privremenih zaslona za ovaj sat.',
    errorNetwork: 'Poslužitelj nije dostupan. Provjeri vezu i pokušaj ponovno.',
    errorInvalid: 'Odabir nije prihvaćen ({field}). Odaberi ponovno.',
    errorFailed: 'Stvaranje zaslona nije uspjelo. Pokušaj ponovno.',
    errorStops: 'Popis stanica nije dostupan.',
    retry: 'Pokušaj ponovno',
    retryIn: 'Pokušaj ponovno za {time}',
    loadingStops: 'Učitavanje stanica…',
    provisionHint: 'Zaslon u prostoru dobiva poveznicu za postavljanje od operatera; ovaj obrazac stvara privremeni zaslon za ocjenjivanje.',
  },
};
