// The 17 gradske četvrti as a build-time-simplified polygon table
// (worker/data/gradske-cetvrti.json, generated by scripts/districts.mjs from
// the offline fixture test/fixtures/gradske_cetvrti.geojson -- see
// docs/izvori.md, "Prostorni slojevi modula ckan-geo"). districtOf() answers
// "which četvrt is this point in" for the Worker's own feed items and
// screen stops so the client never needs the polygons itself (R-DG6): the
// table alone would cost about 25 kB gzip on a `/d/` graph budgeted at
// 200 kB for one lookup per session.
import table from '../../data/gradske-cetvrti.json';
import type { AreaSlug } from '../../pairing/areas';
import type { Geo } from '../schema';

export type Ring = [number, number][]; // closed, [lon, lat]
export type Polygon = Ring[]; // [outer, ...holes]

export interface DistrictPolygon {
  slug: AreaSlug;
  name: string;
  bbox: [number, number, number, number];
  polygons: Polygon[];
}

export interface DistrictTable {
  source: string;
  sourceFixture: 'test/fixtures/gradske_cetvrti.geojson';
  toleranceM: number;
  districts: DistrictPolygon[];
}

export const DISTRICT_TABLE: DistrictTable = table as DistrictTable;

/** A point in a simplification sliver between two districts snaps to the nearest boundary within this. */
export const DISTRICT_SNAP_M = 50;

/** Even-odd ray casting. `ring` is closed (its first and last points coincide). */
export function pointInRing(lon: number, lat: number, ring: Ring): boolean {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i]!;
    const [xj, yj] = ring[j]!;
    const crosses = yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi;
    if (crosses) inside = !inside;
  }
  return inside;
}

/** Inside the outer ring and inside no hole. */
export function pointInPolygon(lon: number, lat: number, polygon: Polygon): boolean {
  const outer = polygon[0];
  if (!outer || !pointInRing(lon, lat, outer)) return false;
  for (let i = 1; i < polygon.length; i += 1) {
    if (pointInRing(lon, lat, polygon[i]!)) return false;
  }
  return true;
}

// Local equirectangular metres around Zagreb's own latitude (45.8°N); good
// enough for the short distances (tens of metres) districtOf's snap pass
// measures. The client keeps its own independent copy of this same
// projection at app/src/motion/geo.ts -- the worker must not import it
// (worker files stay dependency-free of app/src), and scripts/districts.mjs
// keeps a third copy for the same reason (a build script imports neither).
const LON_TO_M = Math.cos((45.8 * Math.PI) / 180) * 111_320;
const LAT_TO_M = 110_574;

function toMetres(lon: number, lat: number): [number, number] {
  return [lon * LON_TO_M, lat * LAT_TO_M];
}

function bboxContains(bbox: readonly [number, number, number, number], lon: number, lat: number, marginM: number): boolean {
  const dLon = marginM / LON_TO_M;
  const dLat = marginM / LAT_TO_M;
  return lon >= bbox[0] - dLon && lon <= bbox[2] + dLon && lat >= bbox[1] - dLat && lat <= bbox[3] + dLat;
}

/** Distance in metres from (lon, lat) to the segment [a, b], both [lon, lat]. */
function pointSegmentDistanceM(lon: number, lat: number, a: readonly [number, number], b: readonly [number, number]): number {
  const [px, py] = toMetres(lon, lat);
  const [ax, ay] = toMetres(a[0], a[1]);
  const [bx, by] = toMetres(b[0], b[1]);
  const dx = bx - ax;
  const dy = by - ay;
  const lengthSq = dx * dx + dy * dy;
  const t = lengthSq === 0 ? 0 : Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / lengthSq));
  const cx = ax + t * dx;
  const cy = ay + t * dy;
  return Math.hypot(px - cx, py - cy);
}

function ringDistanceM(lon: number, lat: number, ring: Ring): number {
  let min = Infinity;
  for (let i = 0; i < ring.length - 1; i += 1) {
    const dist = pointSegmentDistanceM(lon, lat, ring[i]!, ring[i + 1]!);
    if (dist < min) min = dist;
  }
  return min;
}

function polygonDistanceM(lon: number, lat: number, polygon: Polygon): number {
  let min = Infinity;
  for (const ring of polygon) {
    const dist = ringDistanceM(lon, lat, ring);
    if (dist < min) min = dist;
  }
  return min;
}

/**
 * The gradska četvrt containing the point; the nearest within snapM when it
 * falls in a sliver; null outside the city. Bbox pre-check first (expanded
 * by snapM for the snap pass, not for the exact pass). Snap ties resolve by
 * table order: districts are walked in DISTRICT_TABLE's order (AREAS order)
 * and only a strictly closer candidate replaces the current best.
 */
export function districtOf(lon: number, lat: number, snapM = DISTRICT_SNAP_M): AreaSlug | null {
  for (const district of DISTRICT_TABLE.districts) {
    if (!bboxContains(district.bbox, lon, lat, 0)) continue;
    if (district.polygons.some((polygon) => pointInPolygon(lon, lat, polygon))) return district.slug;
  }

  let nearestSlug: AreaSlug | null = null;
  let nearestDistance = Infinity;
  for (const district of DISTRICT_TABLE.districts) {
    if (!bboxContains(district.bbox, lon, lat, snapM)) continue;
    let distance = Infinity;
    for (const polygon of district.polygons) {
      const polygonDistance = polygonDistanceM(lon, lat, polygon);
      if (polygonDistance < distance) distance = polygonDistance;
    }
    if (distance <= snapM && distance < nearestDistance) {
      nearestDistance = distance;
      nearestSlug = district.slug;
    }
  }
  return nearestSlug;
}

/** Point: itself. LineString: its first vertex (a closure is filed where it starts). */
export function districtOfGeo(geo: Geo | undefined): AreaSlug | null {
  if (!geo) return null;
  if (geo.type === 'Point') {
    const [lon, lat] = geo.coordinates as [number, number];
    return districtOf(lon, lat);
  }
  const first = (geo.coordinates as number[][])[0];
  if (!first) return null;
  return districtOf(first[0]!, first[1]!);
}
